models/modulo.py
from utils.db import db
    
class Modulo(db.Model):
    id_mod = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(30))    

    def __init__(self, id_mod, nombre=None) -> None:
        self.id_mod = id_mod
        self.nombre = nombre

models/rol.py
from utils.db import db
    
class Rol(db.Model):
    id_rol = db.Column(db.Integer, primary_key=True)
    descripcion = db.Column(db.String(60))    

    def __init__(self, id_rol, descripcion=None) -> None:
        self.id_rol = id_rol
        self.descripcion = descripcion

models/usuario.py
from utils.db import db
    
class Usuario(db.Model):
    id_usuario = db.Column(db.Integer, primary_key=True)
    user_name = db.Column(db.String(300))
    password = db.Column("password",db.String(50)) #usamos el alias 'pass' para que los reconozca la BD

    def __init__(self, id_usuario, user_name=None, password=None) -> None:
        self.id_usuario = id_usuario
        self.user_name = user_name
        self.password = password
        

    

models/usuarioModulo.py
from utils.db import db

class Usuario_Modulo(db.Model):
    id_usuario = db.Column(db.Integer, primary_key=True)
    id_modulo = db.Column(db.Integer, primary_key=True)
    estado_up = db.Column(db.Boolean)
    fecha_inicio = db.Column(db.Date)
    fecha_cambio = db.Column(db.Date)

    def __init__(self, id_usuario, id_modulo, estado_up = None, fecha_inicio = None, fecha_cambio = None) -> None:
        self.id_usuario = id_usuario
        self.id_modulo = id_modulo
        self.estado_up = estado_up
        self.fecha_inicio = fecha_inicio
        self.fecha_cambio = fecha_cambio

models/usuarioRol.py
from utils.db import db

class Usuario_Rol(db.Model):
    id_usuario = db.Column(db.Integer, primary_key=True)
    id_rol = db.Column(db.Integer, primary_key=True)
    estado_up = db.Column(db.Boolean)
    fecha_inicio = db.Column(db.Date)
    fecha_cambio = db.Column(db.Date)

    def __init__(self, id_usuario, id_rol, estado_up = None, fecha_inicio = None, fecha_cambio = None) -> None:
        self.id_usuario = id_usuario
        self.id_rol = id_rol
        self.estado_up = estado_up
        self.fecha_inicio = fecha_inicio
        self.fecha_cambio = fecha_cambio


    

app.py
from flask import Flask
from utils.config import Config

from routes import login, index, portal, vista, mainmenu, infoCondosa,login2

def crear_app():
    app = Flask(__name__)

    app.static_folder = 'static'

    app.config.from_object(Config)

    app.register_blueprint(login.bp)
    app.register_blueprint(login2.bp)
    app.register_blueprint(index.bp)
    app.register_blueprint(portal.bp)
    app.register_blueprint(vista.bp)
    app.register_blueprint(mainmenu.bp)
    app.register_blueprint(infoCondosa.bp)

    return app

routes/index.py
from flask import Blueprint, render_template as rt

bp = Blueprint('index', __name__) #al llamar el blue print en base sería (NomreBP.FuncionAsociadaARuta)

@bp.route('/')
def index():
    return rt("index.html")

routes/infoCondosa.py
from flask import Blueprint, render_template as rt

bp = Blueprint('infoCondosa', __name__, url_prefix="/infoCondosa") #al llamar el blue print en base sería (NomreBP.FuncionAsociadaARuta)

@bp.route('/')
def infoCondosa():
    return rt("infoCondosa.html")

routes/login.py
from flask import session, Blueprint, render_template as rt, request, url_for, redirect
from flask import Blueprint, render_template as rt, request, url_for, redirect

from models.usuario import Usuario

bp = Blueprint('login', __name__,url_prefix="/login") #al llamar el blue print en base sería (NomreBP.FuncionAsociadaARuta)

@bp.route('/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        usuario = Usuario.query.filter_by(user_name=f"{email}@condosa.com").first()
        if usuario:
            d_password = usuario.password
            if password == d_password:
                print("Éxito")
                session['logged_in'] = True
                return redirect(url_for('mainmenu.mainmenu'))
            else:
                print("Fallo")
                
        else:
            print("Fallo")

    return rt("login.html")

routes/login2.py
from flask import session, Blueprint, render_template as rt, request, url_for, redirect
from flask import Blueprint, render_template as rt, request, url_for, redirect

from models.usuario import Usuario

bp = Blueprint('login2', __name__,url_prefix="/login2") #al llamar el blue print en base sería (NomreBP.FuncionAsociadaARuta)

@bp.route('/', methods=['GET', 'POST'])
def login2():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        usuario = Usuario.query.filter_by(user_name=f"{email}@gmail.com").first()
        if usuario:
            d_password = usuario.password
            if password == d_password:
                print("Éxito")
                session['logged_in'] = True
                return redirect(url_for('mainmenu.mainmenu'))
            else:
                print("Fallo")
                
        else:
            print("Fallo")

    return rt("login2.html")

routes/mainmenu.py
from flask import session, Blueprint, render_template as rt, request, url_for, redirect
from flask import Blueprint, render_template as rt
from utils.auth import login_required

bp = Blueprint('mainmenu', __name__, url_prefix="/mainmenu")

@bp.route('/', methods=['GET', 'POST'])
@login_required
def mainmenu():
    if request.method == 'POST':
                session.clear()
                return redirect(url_for('index.index'))
    return rt("mainmenu.html")

routes/portal.py
from flask import Blueprint, render_template as rt

bp = Blueprint('portal', __name__, url_prefix="/portal") #al llamar el blue print en base sería (NomreBP.FuncionAsociadaARuta)

@bp.route('/')
def portal():
    return rt("portal.html")

routes/vista.py
from flask import Blueprint, jsonify

from models.usuario import Usuario
from models.modulo import Modulo
from models.rol import Rol
from models.usuarioRol import Usuario_Rol
from models.usuarioModulo import Usuario_Modulo

from utils.db import db
from utils.json import model_to_dict

bp = Blueprint('vista',__name__, url_prefix="/vista")

@bp.route('/')
def vista():
    usuario = Usuario.query.all()
    usuario_rol = Usuario_Rol.query.all()
    modulo = Modulo.query.all()

    data_usuario_rol = []
    data_usuario = []
    data_modulo = []

    for obj in usuario_rol:
        x = model_to_dict(obj)
        data_usuario_rol.append(x)

    for obj in usuario:
        x = model_to_dict(obj)
        data_usuario.append(x)

    for obj in modulo:
        x = model_to_dict(obj)
        data_modulo.append(x)    

    result = {
        'Usuario':data_usuario,
        'Rol_Usuario':data_usuario_rol,
        'Modulo':data_modulo
    }

    return jsonify(result)

@bp.route('/usuario')
def vista_usuario():
    query = Usuario.query.all()
    data = []
    for obj in query:
        data.append(model_to_dict(obj))
    result = {
        'Usuario': data
    }
    return jsonify(result)

@bp.route('/modulo')
def vista_modulo():
    query = Modulo.query.all()
    data = []
    for obj in query:
        data.append(model_to_dict(obj))
    result = {
        'Modulo': data
    }
    return jsonify(result)

@bp.route('/rol')
def vista_rol():
    query = Rol.query.all()
    data = []
    for obj in query:
        data.append(model_to_dict(obj))
    result = {
        'Rol': data
    }
    return jsonify(result)

@bp.route('/usuario_modulo')
def vista_usuario_modulo():
    query = Usuario_Modulo.query.all()
    data = []
    for obj in query:
        data.append(model_to_dict(obj))
    result = {
        'Usuario_Modulo': data
    }
    return jsonify(result)

@bp.route('/usuario_rol')
def vista_usuario_rol():
    query = Usuario_Rol.query.all()
    data = []
    for obj in query:
        data.append(model_to_dict(obj))
    result = {
        'Usuario_Rol': data
    }
    return jsonify(result)

utils/auth.py
from functools import wraps
from flask import session, redirect, url_for

def login_required(view):
    @wraps(view)
    def wrapped_view(*args, **kwargs):
        if 'logged_in' in session:
            return view(*args, **kwargs)
        else:
            #return redirect(url_for('portal.portal'))
            return redirect(url_for('login.login'))
    return wrapped_view

templates/footer.html
<!-- footer.html -->
<footer class=" d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top w-100" style="background-color: #38373b;">
    <div class="d-flex align-items-center">
        <a href="{{url_for('index.index')}}" class="d-inline-flex link-body-emphasis text-decoration-none">
            <img class="" src="{{ url_for('static', filename='img/condosa.png') }}" alt="" width="162" height="67">
        </a>
     
    </div>
  
    <ul class="nav justify-content-center mx-auto">
      <li class="nav-item"><a href="{{url_for('index.index')}}" class="nav-link px-2  text-white">INICIO</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2  text-white">QUÍENES SOMOS</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2  text-white">PROYECTOS EN VENTA</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2  text-white">PROYECTOS ENTREGADOS</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2  text-white">CONTACTO</a></li>
    </ul>
  
    <div class="social-icons">
      <a href="#" class="social-icon me-2"><i class="fab fa-facebook-f fa-lg text-white"></i></a>
      <a href="#" class="social-icon me-2"><i class="fab fa-instagram fa-lg text-white"></i></a>
      <a href="#" class="social-icon me-2"><i class="fab fa-whatsapp fa-lg text-white"></i></a>
    </div>
  </footer>

templates/index.html
{% extends "layout.html" %}

{% block body %}
<div class=" container-fluid">

<div id="carouselExampleIndicators" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{ url_for('static', filename='img/carrusel1.jpg') }}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{{ url_for('static', filename='img/carrusel2.jpg') }}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{{ url_for('static', filename='img/carrusel3.jpg') }}" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>
{% endblock %}

templates/infoCondosa.html
{% extends "layout.html" %}

{% block body %}

<!-- TOdo el quienes somos -->
<div class="container py-5">
    <div class="card mb-3 " width="100" >
      <div class="row g-0">
        <div class="col-md-4">
          <img src="{{ url_for('static', filename='img/somos.png') }}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h2 class="card-title text-center">Constructora Condosa</h2>
            <p class="card-text" >Constructora Condosa, se constituye en Enero del 2018 por la familia Ortiz Heerwagen en la ciudad de Concepción. Empresa familiar, 
              ligada al rubro de la Construcción e Inmobiliario desde los años setenta, siendo Constructora e Inmobiliaria el Parque la última sociedad donde participó, 
              desarrollando cerca de 20 proyectos inmobiliarios en el gran Concepción.</p>
              <img class="text-center" src="{{ url_for('static', filename='img/condosab.jpg') }}" alt="" >
              <p class="lead">Te invitamos a conocer nuestros<a href="{{url_for('index.index')}}" class="text-bg-secondary active"> Proyectos entregados.</a>
              </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container py-lg-5">

  </div>
  <div class="container py-2">

  </div>
  <!-- hasta aca el quien -->
  {% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Condosa</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>

<body>
  <div class="container-fluid" style="background-color: #2e0f9e;">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 ">
      <div class="col-md-3 mb-2 mb-md-0">
        <!-- POner Logo nota -->
        <a href="{{url_for('index.index')}}" class="d-inline-flex link-body-emphasis text-decoration-none">
            <img class="mb-4" src="{{ url_for('static', filename='img/condosa.png') }}" alt="" width="162" height="67">
        </a>
      </div>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0 text-white">
        <li><a href="{{url_for('index.index')}}" class="nav-link px-4 text-white  active">Inicio</a></li>
        <li><a href="{{url_for('infoCondosa.infoCondosa')}}" class="nav-link px-4 text-white  active">Quiénes somos</a></li>
        <li><a href="#" class="nav-link px-4 text-white  active">Precios</a></li>
        <li><a href="#" class="nav-link px-4 text-white  active">Preguntas Frecuentes</a></li>
        <li><a href="#" class="nav-link px-4 text-white  active">Acerca de</a></li>

      </ul>

      <div class="col-md-3 text-end">
        <!-- Los botones deben usar una función en Onclick para redireccionar -->
        <a href="{{url_for('portal.portal')}}" class="btn btn-outline-primary me-2 text-white ">Iniciar sesión </a>
        <a href="#" class="btn btn-primary">Regístrate</a>
      </div>
    </header>
  </div>
  <div class="container" width="80%">
    {% block body %}
    {% endblock %}
  </div>
  <div class="container-fluid">
    {% block footer %}
      {% include 'footer.html' %}
    {% endblock %}
  </div>


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" 
  integrity="sha384-KyZb8+oLOoJh3ZOWn8vvsPiAJbQXCkCDfVNC6PO6x2Q7gB1rx5Z5ERJTP6ZplQnw" crossorigin="anonymous"></script>

</body>

</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}

<div class="w-25 container py-lg-5">
    <main class="form-signin text-center">
      <form method="POST" action="{{ url_for('login.login') }}">
        <img class="mb-4" src="{{ url_for('static', filename='img/casa.png') }}" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">Ingresa tu usuario</h1>
        <div class="input-group mb-3">
          <input type="text" name="email" class="form-control custom-input" id="floatingInput" placeholder="Usuario">
          <span class="input-group-text">@condosa.com</span>
        </div>
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control custom-input" id="floatingPassword" placeholder="Contraseña">
        </div>
        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Recuérdame
          </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Ingresar</button>
        <p class="mt-5 mb-3 text-muted">© 2023 CONDOSA. Todos los derechos reservados</p>
      </form>
    </main>
  </div>
  <div class="container py-lg-5">
  </div>
  <div class="container py-lg-3">
  </div>

  <style>
    .custom-input {
  width: 100%;
}
  </style>
{% endblock %}

templates/login2.html
{% extends "layout.html" %}

{% block body %}

<div class="w-25 container py-lg-5">
    <main class="form-signin text-center">
      <form method="POST" action="{{ url_for('login2.login2') }}">
        <img class="mb-4" src="{{ url_for('static', filename='img/casa.png') }}" alt="" width="72" height="57">
        <h1 class="h3 mb-3 fw-normal">Ingresa tu usuario</h1>
        <div class="input-group mb-3">
          <input type="text" name="email" class="form-control custom-input" id="floatingInput" placeholder="Usuario">
          <span class="input-group-text">@gmail.com</span>
        </div>
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control custom-input" id="floatingPassword" placeholder="Contraseña">
        </div>
        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Recuérdame
          </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Ingresar</button>
        <p class="mt-5 mb-3 text-muted">© 2023 CONDOSA. Todos los derechos reservados</p>
      </form>
    </main>
  </div>
  <div class="container py-lg-5">
  </div>
  <div class="container py-lg-3">
  </div>

  <style>
    .custom-input {
  width: 100%;
}
  </style>
{% endblock %}

templates/mainmenu.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>

<body>
  <div class="container-fluid" style="background-color: #2e0f9e;">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 ">
      <div class="col-md-3 mb-2 mb-md-0">
        <!-- POner Logo nota -->
        <a href="/img/casa.png" class="d-inline-flex link-body-emphasis text-decoration-none">
          <svg class="bi" width="40" height="32" role="img" aria-label="Bootstrap">
            <use xlink:href="#"></use>
          </svg>
        </a>
      </div>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0 text-white">
        <li><a href="#" class="nav-link px-4 text-white  active">Inicio</a></li>
        <li><a href="/Templates/iniciar.html" class="nav-link px-4 text-white  active">Quiénes somos</a></li>
        <li><a href="#" class="nav-link px-4 text-white  active">Precios</a></li>
        <li><a href="#" class="nav-link px-4 text-white  active">Preguntas Frecuentes</a></li>
        <li><a href="#" class="nav-link px-4 text-white  active">Acerca de</a></li>

      </ul>

      <div class="col-md-3 text-end">
        <!-- Los botones deben usar una función en Onclick para redireccionar -->
        <a href="#" class="btn btn-primary">Iniciar sesión </a>
        <button type="button" class="btn btn-primary" onclick="">Regístrate</button>
      </div>
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          Nombre de Usuario
        </button>
        <!-- Opciones del perfil -->
        <ul class="dropdown-menu dropdown-menu-end">
          <li><a class="dropdown-item" href="#"><i class="fas fa-user"></i> Mi perfil</a></li>
          <li><a class="dropdown-item" href="#"><i class="fas fa-cog"></i> Configuraciones</a></li>
          <li>
            <form method="POST" action="{{ url_for('mainmenu.mainmenu') }}">
              <button class="dropdown-item" type="submit"><i class="fas fa-sign-out-alt"></i> Cerrar Sesión</button>
            </form>
          </li>
        </ul>
      </div>
    </header>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
  crossorigin="anonymous"></script>
</body>

</html>

templates/portal.html
{% extends "layout.html" %}

{% block body %}

<div class="container py-lg-5">
  <div class="d-flex flex-row justify-content-center">
    <div class="card text-bg-dark mx-auto">
      <img src="{{ url_for('static', filename='img/Admin.jpg') }}" class="card-img" alt="...">
      <div class="card-img-overlay">
        <h5 class="card-title">Administrador</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <a href="{{url_for('login.login')}}" class="btn btn-primary">Ingresar</a>
      </div>
    </div>

    <div class="card text-bg-dark mx-auto">
      <img src="{{ url_for('static', filename='img/Personal.jpg') }}" class="card-img" alt="...">
      <div class="card-img-overlay">
        <h5 class="card-title">Personal</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <a href="{{url_for('login.login')}}" class="btn btn-primary">Ingresar</a>
      </div>
    </div>

    <div class="card text-bg-dark mx-auto">
      <img src="{{ url_for('static', filename='img/Cliente.jpg') }}" class="card-img" alt="...">
      <div class="card-img-overlay">
        <h5 class="card-title">Cliente</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <a href="{{url_for('login2.login2')}}" class="btn btn-primary">Ingresar</a>
      </div>
    </div>
  </div>
</div>
<div class="container py-lg-5">
</div>
<div class="container py-lg-5">
</div>
<div class="container py-lg-1">
</div>

<style>
    .card {
    width: 300px;
    height: 400px;
  }
  
  .card-img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    opacity: 0.5; 
  }

  .card-title,
  .card-text {
    color: white;
  }

</style>

{% endblock %}